services:
  - docker

before_install:
  - docker pull gcc:7.4.0
  - docker run --rm --name gcc-test -v $(pwd):/app --entrypoint='/bin/sh' gcc:7.4.0 -c 'g++ -g -std=gnu++11 /app/test/main/test-main.o -o /app/test/allTests -I /app/include /app/src/config/*.cpp /app/src/device/*.cpp /app/test/unit/mocks/*.cpp /app/test/unit/*.cpp'

script:
  - $(pwd)/test/allTests
